### ISSUE TITLE
Import File Tasks

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#2078]
The code has been refactored to include an infrastructure the wizard is built upon.

The code is being worked on the hackathon/amir/flatfile branch.

Tasks remaining to make this shippable:

- [x] Localize strings.
- [x] Support remembering information when the user presses "Import another file".
- [ ] Add a horizontal scrolling bar on the prose preview page (#2073).
- [ ] Add another event to wizards to be fired when the wizard is opened and when the wizard is closed (#2079).
- [ ] Text fields don't update if the user doesn't click outside of them (#2080).
- [x] Next button is not initially disabled when required fields are empty (#2041).
- [ ] Create a testing system around the extension.

**Comment by kburtram** [comment]
Closing old tasks that aren't currently being tracked.
