### ISSUE TITLE
cell selection and navigation issues with query result grid

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#20855]
- [ ] Can't use mouse select button to select cells that span cross multiple pages.  refer to Excel for the desired behavior
![select-multiple-pages-with-mouse](https://user-images.githubusercontent.com/13777222/195955527-9504e15d-cf02-4135-b663-158ad320554f.gif)

- [ ] Use mouse select button and mouse wheel/page up down key to select a range, the focus will be moved out of the grid. original issue: https://github.com/microsoft/azuredatastudio/issues/5882
- [ ] Not able to select the entire rows or columns using keyboard only. Refer to excel: introduce keyboard shortcuts: SHIFT+Space -> select active rows, CTRL/CMD+Space -> select active columns
- [ ] Navigate with keyboard doesn't reset the selected cells, original issues: https://github.com/microsoft/azuredatastudio/issues/14541
- [ ] Hold down Page Up/Down will cause the focus to disappear from the grid. https://github.com/microsoft/azuredatastudio/issues/20611, https://github.com/microsoft/azuredatastudio/issues/3705
- [ ] Up/Down key is not moving the focus to the cell in the same column of above/below row: https://github.com/microsoft/azuredatastudio/issues/2550
