### ISSUE TITLE
Add Create Database dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23248]
```[tasklist]
### Tasks
- [x] Enable basic dialog experience
- [ ] https://github.com/microsoft/azuredatastudio/issues/23327
- [ ] https://github.com/microsoft/azuredatastudio/issues/23328
- [ ] https://github.com/microsoft/azuredatastudio/issues/23331
```
