### ISSUE TITLE
Add Delete Database dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23251]
```[tasklist]
### Tasks
- [x] Add basic Delete functionality to database context menu
- [ ] https://github.com/microsoft/azuredatastudio/issues/23329
- [ ] https://github.com/microsoft/azuredatastudio/issues/23330
```

**Comment by corivera** [comment]
Already added Delete to the database context menu a while back.
