### ISSUE TITLE
MSSQL Backup dialog improvements

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23252]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azuredatastudio/issues/24588
- [ ] https://github.com/microsoft/azuredatastudio/issues/24589
- [ ] https://github.com/microsoft/azuredatastudio/issues/24590
```
