### ISSUE TITLE
MSSQL Restore dialog improvements

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23253]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azuredatastudio/issues/24591
- [ ] https://github.com/microsoft/azuredatastudio/issues/24592
- [ ] https://github.com/microsoft/azuredatastudio/issues/24593
```
