### ISSUE TITLE
Add Server properties dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23256]
```[tasklist]
### Tasks
- [x] Add General Tab
- [x] Add Memory Tab
- [x] Update values min and max memory values in Server Dialog
```

```[tasklist]
### Tasks
- [x] Remove stub values from the ServerPropertiesDialog
- [ ] https://github.com/microsoft/azuredatastudio/issues/24131
- [ ] https://github.com/microsoft/azuredatastudio/issues/24130
- [ ] https://github.com/microsoft/azuredatastudio/issues/24129
```
