### ISSUE TITLE
Add Database properties dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23254]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azuredatastudio/issues/23319
- [ ] https://github.com/microsoft/azuredatastudio/issues/23337
- [ ] https://github.com/microsoft/azuredatastudio/issues/23340
- [ ] https://github.com/microsoft/azuredatastudio/issues/23338
- [ ] https://github.com/microsoft/azuredatastudio/issues/23341
- [ ] https://github.com/microsoft/azuredatastudio/issues/23339
- [ ] https://github.com/microsoft/azuredatastudio/issues/23342
- [ ] https://github.com/microsoft/azuredatastudio/issues/23790
```

**Comment by ssreerama** [comment]
Added all required tabs to the properties dialog, please refer each individual tasks for their PRs and issues.
