### ISSUE TITLE
Big issues

### ISSUE THREAD

**Issue by markjpT** [microsoft/azuredatastudio#24506]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/azuredatastudio/issues/21691
- [ ] https://github.com/microsoft/azuredatastudio/issues/24493
- [ ] https://github.com/microsoft/azuredatastudio/issues/24504
- [ ] https://github.com/microsoft/azuredatastudio/issues/24503
- [ ] https://github.com/microsoft/azuredatastudio/issues/24476
- [ ] https://github.com/microsoft/azuredatastudio/pull/24505
- [ ] https://github.com/microsoft/azuredatastudio/issues/18524
- [ ] https://github.com/microsoft/azuredatastudio/issues/24436
- [ ] https://github.com/microsoft/azuredatastudio/pull/24499
- [ ] https://github.com/microsoft/azuredatastudio/issues/24009
```

**Comment by markjpT** [comment]
Done
