### ISSUE TITLE
Unified connection for SQL 2019 BCD

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3707]
This is an overall tracker for status of the unified connection work

**Tasks**
Feb release
- [x] Implement expander APIs - Feb release
- [x] Query big data endpoints in sqlops-dataprotocolclient - Feb release
- [x] Notebook add new connection: -Feb release
- [x] Notebook attach to handle OE unified connection - Feb release
- [x] Dashboard adds big data cluster tasks and links - Feb release
- [x] Server context menu add new Notebook and submit spark job
- [x] Data Services context menu - File operations
- [x] Remove the above file operation from Aris HDFS context menu
- [x] OE error node - Need to talk with PM on UI
- [ ] Add integration and unit tests for new APIs - Feb release

March
- [x] webHDFS folder icon
- [x] Remove big data option from connectionDialog
- [ ] Server icon differentiate box, cloud and BDC

TBD based on platform schedule
- [ ] Support different authentication types: integrated and AAD auth
- [ ] Self-signed cert - need to check with core team to find out the timeline

Cleanup work
- [ ] Enable user credential check in isMatch for file operations when unified user is available from Platform team

**Comment by kevcunnane** [comment]
Closing this - majority of work done, everything else is split into separate items.
