### ISSUE TITLE
Schema Compare enhancements checklist

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#5481]
Following are the things to target for upcoming schema compare release 

- [x] Source and Target taking up too much vertical space in Schema Compare document 

- [x] Avoid having the double scrollbars in main page. Have good default proportions between SQL text area and change table

- [x] Avoid having double scrollbar in options page

- [x] Toolbar should always be visible and not hidden when document is scrolled. 

- [x] Generated Script should open after being generated. 

- [ ] Schema Compare title bar document should have non-default icon 

- [x] Save As doesn’t remember previously used folder (Script is opened instead of saved now)

- [x] Changing Options didn’t take effect generated scripts until Compare is run again 

- [x] Reset button in options

- [x] Disable Okay button if source/target isn't selected 

- [x] Schema compare first dialog window text formatting 

- [x] Add Exclude/Include options

**Comment by udeeshagautam** [comment]
Since all of these are done and only one remaining - **Schema Compare title bar document should have non-default icon** will **not** be a part of June - so closing the overall task and adding the one remaining to July checklist
