### ISSUE TITLE
Schema compare next milestone checklist

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#5729]
Some of these are from previous release and some from User study. 

**To Do**

- [x] Schema Compare title bar document should have non-default icon

- [x] Drop down in Schema compare page for source target (or open start dialog?)

- [x] Dropdown for server/db to allow typing to filter in case of long list

- [x] Stop cancel on Compare

- [x] Databases should be in alphabetical (or same as OE) order

- [x] Saving/Loading settings (SCMP)/ customized set of options

- [x] Fix Diff Table margin [UX]

**To Investigate (These are not supported in SSDT)**

Moving these to separate enhancement for clarity in milestones : https://github.com/microsoft/azuredatastudio/issues/5938

**Comment by udeeshagautam** [comment]
Closing this since all line items are now checked. Will track individual bugs separately.
