### ISSUE TITLE
Compile workbench/services and contrib under strict options

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#9169]
How To:
Goal here is to compile our code how vscode does which is far more strict. We can do this on a folder by folder basis by modifying `src/tsconfig.vscode.json`. Currently I am including everything in `workbench/services` and `workbench/contrib` and then excluding the folders that currently are throwing errors. In order to address the issues in a folder, remove it from the exclude and run `yarn strict-vscode` which will throw errors (alternatively there is a vscode task `TS - strict vscode` that is a watch). Fix these errors then make a PR.

This check runs as part of CI so once an area is no longer throwing errors, the CI will fail if someone regresses the area.

- [ ] `./sql/workbench/api/browser/**/*.ts`, _**942 errors**_
- [ ] `./sql/workbench/api/common/**/*.ts`, _**236 errors**_
- [ ] `./sql/workbench/browser/**/*.ts`, _**2646 errors**_
- [ ] `./sql/workbench/contrib/assessment/**/*.ts`, _**62 errors**_
- [ ] `./sql/workbench/contrib/commandLine/**/*.ts`, _**292 errors**_ @aasimkhan30 
- [ ] `./sql/workbench/contrib/connection/**/*.ts`, _**174 errors**_
- [ ] `./sql/workbench/contrib/dashboard/**/*.ts`, _**1015 errors**_
- [ ] `./sql/workbench/contrib/dataExplorer/**/*.ts`, _**2667 errors**_
- [ ] `./sql/workbench/contrib/editData/**/*.ts`, _**441  errors**_
- [ ] `./sql/workbench/contrib/jobManagement/**/*.ts`, _**315 errors**_ @abist 
- [ ] `./sql/workbench/contrib/modelView/**/*.ts`, _**2646 errors**_
- [ ] `./sql/workbench/contrib/notebook/**/*.ts`, _**2648 errors**_
- [ ] `./sql/workbench/contrib/profiler/**/*.ts`, _**101 errors**_ @alanrenmsft 
- [ ] `./sql/workbench/contrib/query/**/*.ts`, _**483 errors**_
- [ ] `./sql/workbench/contrib/queryHistory/**/*.ts`, _**291 errors**_ @Charles-Gagnon 
- [ ] `./sql/workbench/contrib/welcome/**/*.ts`, _**66 errors**_
- [ ] `./sql/workbench/services/connection/**/*.ts`, _**253 errors**_
- [ ] `./sql/workbench/services/dialog/**/*.ts`, _**82 errors**_
- [ ] `./sql/workbench/services/fileBrowser/**/*.ts`, _**2646 errors**_
- [ ] `./sql/workbench/services/insights/**/*.ts`, _**67 errors**_
- [ ] `./sql/workbench/services/notebook/**/*.ts`, _**200 errors**_ @lucyzhang929 
- [ ] `./sql/workbench/services/objectExplorer/**/*.ts`, _**185 errors**_ @aaomidi 
- [ ] `./sql/workbench/test/**/*.ts`, _**2975 errors**_
- [ ] `./sql/workbench/update/**/*.ts`, _**2646 errors**_

Complete
- [x] ~`./sql/workbench/contrib/azure/**/*.ts`, _**118 errors**_ @aaomidi #11928~
- [x] ~`./sql/workbench/contrib/backup/**/*.ts`, _**89 errors**_ #12088~
- [x] ~`./sql/workbench/contrib/charts/**/*.ts`, _**63 errors**_ #12167~
- [x] ~`./sql/workbench/contrib/configuration/**/*.ts`, _**2 errors**_ #11915~
- [x] ~`./sql/workbench/contrib/editorReplacement/**/*.ts`, _**6 errors**_ #12166~
- [x] ~`./sql/workbench/contrib/extensions/**/*.ts`, _**45 errors**_ #11916~
- [x] ~`./sql/workbench/contrib/preferences/**/*.ts`, _**1 errors**_ #11915~
- [x] ~`./sql/workbench/contrib/queryPlan/**/*.ts`, _**52 errors**_ #11917~
- [x] ~`./sql/workbench/contrib/restore/**/*.ts`, _**28 errors**_#12044~
- [x] ~`./sql/workbench/contrib/scripting/**/*.ts`, _**179 errors**_#12126~
- [x] ~`./sql/workbench/contrib/tasks/**/*.ts`, _**8 errors**_ #12034~
- [x] ~`./sql/workbench/contrib/views/**/*.ts`, _**19 errors**_#12044~
- [x] ~`./sql/workbench/contrib/webview/**/*.ts`, _**6 errors**_ #11921~
- [x] ~`./sql/workbench/services/queryEditor/**/*.ts`, _**10 errors**_ #12166~
- [x] ~`./sql/workbench/services/restore/**/*.ts`, _**83 errors**_ #12067~

VS Code

- [ ] `./vs/workbench/api/browser/**/*.ts`, _**3271 errors**_
- [ ] `./vs/workbench/api/common/**/*.ts`, _**323 errors**_
- [ ] `./vs/workbench/api/node/**/*.ts`, _**328 errors**_
- [ ] `./vs/workbench/api/worker/**/*.ts`, _**294 errors**_
- [ ] `./vs/workbench/contrib/backup/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/codeEditor/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/comments/**/*.ts`, _**64 errors**_
- [ ] `./vs/workbench/contrib/configExporter/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/customEditor/**/*.ts`, _**99 errors**_
- [ ] `./vs/workbench/contrib/debug/**/*.ts`, _**3136 errors**_
- [ ] `./vs/workbench/contrib/experiments/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/extensions/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/files/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/issue/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/logs/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/notebook/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/outline/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/performance/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/preferences/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/relauncher/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/remote/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/search/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/searchEditor/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/splash/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/tags/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/tasks/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/telemetry/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/terminal/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/timeline/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/update/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/url/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/userDataSync/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/watermark/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/webview/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/contrib/welcome/**/*.ts`, _**65 errors**_
- [ ] `./vs/workbench/electron-browser/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/electron-sandbox/**/*.ts`, _**3246 errors**_
- [ ] `./vs/workbench/browser/**/*.ts`, _**3246 errors**_

**Comment by Charles-Gagnon** [comment]
Closing older engineering-focused items
